/*********************************************************************
	Rhapsody	: 8.1.5
	Login		: amathieu
	Component	: DefaultComponent
	Configuration 	: DefaultConfig
	Model Element	: Facture
//!	Generated Date	: Wed, 3, May 2017 
	File Path	: DefaultComponent/DefaultConfig/vue/Facture.java
*********************************************************************/

package vue;
import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import model.Consomateur;

//----------------------------------------------------------------------------
// vue/Facture.java                                                                  
//----------------------------------------------------------------------------

//## package vue 


//## class Facture 
public class Facture {
	
	private static String FILE = "//qnap/home/Documents/facture/facture.pdf";
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    // Constructors
    private Consomateur consommateur;
    private int consommation;
    //## auto_generated 
    public  Facture(Consomateur c,int conso) {
    	this.consommateur = c;
    	this.consommation = conso;
    }
    
    public void imprimer(){
    	try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            addMetaData(document);
            addTitlePage(document);
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }
    
    private void addTitlePage(Document document)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Facture", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Facture du : " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        addEmptyLine(preface, 2);
        preface.add(new Paragraph(
                "IdClient : "+this.consommateur.getId(),
                smallBold));
        preface.add(new Paragraph(
                "Nom : "+this.consommateur.getNom(),
                smallBold));
        preface.add(new Paragraph(
                "Prenom : "+this.consommateur.getPrenom(),
                smallBold));        
        addEmptyLine(preface, 2);       
        preface.add(new Paragraph(
                "IdFournisseur : "+this.consommateur.getFournisseur().getId(),
                smallBold));
        preface.add(new Paragraph(
                "Fournisseur : "+this.consommateur.getFournisseur().getNom(),
                smallBold));
        addEmptyLine(preface, 3);       
        preface.add(new Paragraph(
                "Consommation : "+this.consommation+" kw",
                smallBold));
        preface.add(new Paragraph(
                "Pric du forfait : "+this.consommateur.getFournisseur().getTarif()+" €",
                smallBold));
        addEmptyLine(preface, 5);  
        preface.add(new Paragraph(
                "Cette facture est officiellement généré par les compteurs Elektek",
                redFont));
        document.add(preface);
        // Start a new page
        document.newPage();
    }

    
    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
    
}
/*********************************************************************
	File Path	: DefaultComponent/DefaultConfig/vue/Facture.java
*********************************************************************/

